# Generated by Django 3.1.2 on 2022-04-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Division', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('difficulty_level', models.CharField(blank=b'I00\n', choices=[('B', 'BASIC'), ('I', 'INTERMEDIAT'), ('A', 'ADVANCED'), ('E', 'EXPERT')], default='B', help_text='Level of Dificulty', max_length=1)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.author')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
        ),
    ]
