# Generated by Django 3.1.2 on 2022-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220402_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
