# Generated by Django 3.1.2 on 2022-04-15 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220402_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='options',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(29999)]),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='answer',
            field=models.TextField(max_length=200),
        ),
    ]
