# Generated by Django 3.1.2 on 2022-04-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20220415_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_question',
            old_name='options',
            new_name='opt1',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='opt2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='opt3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='opt4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
