# Generated by Django 3.1.2 on 2022-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20220417_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question',
            name='extra',
            field=models.CharField(help_text='Some extra interesting  info on the answer', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='difficulty_level',
            field=models.CharField(blank=b'I00\n', choices=[('BASIC', 'BASIC'), ('INTR', 'INTERMEDIAT'), ('ADV', 'ADVANCED'), ('EXPERT', 'EXPERT')], default='BASIC', help_text='Level of Dificulty to be juged by the author', max_length=6),
        ),
    ]
