# Generated by Django 3.2.5 on 2022-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quiz_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
